### ISSUE TITLE
How to do the active learning and LLM annotation by myself?

### ISSUE THREAD

**Issue by lannester666** [CurryTang/LLMGNN#4]
Hi, thanks for your great work! In readme you suggest we use your cached openai response and active learning result, but I'm curious about how to generate these two files by myself. Could you give an example to show how to do this?

**Comment by ALLISWELL8** [comment]
I have the same problem.

**Comment by CurryTang** [comment]
Most of the logic should be in the `llm.py` file. I will update the readme when having some spare time.
